### ISSUE TITLE
##[error]A supported task execution handler was not found. The task does not carry an implementation that is compatible with your current operating system 'Windows'.

### ISSUE THREAD

**Issue by xpleonix** [huserben/TfsExtensions#200] opened 2021-12-20 09:04 UTC
Hi,
All trigger tasks have been failing since yesterday's update:

2021-12-19T07:31:43.4075429Z ##[section]Starting: Trigger a new build of Update servers
2021-12-19T07:31:43.4083960Z ==============================================================================
2021-12-19T07:31:43.4084464Z Task         : Trigger Build
2021-12-19T07:31:43.4084612Z Description  : This tasks allows to trigger a new Build (add it to the queue) as part of a Build Definition. It contains as well some conditions that can be applied, for example if the last build of certain definition was successful or not.
2021-12-19T07:31:43.4084734Z Version      : 3.3.0
2021-12-19T07:31:43.4084804Z Author       : Benjamin Huser
2021-12-19T07:31:43.4084921Z Help         : 
2021-12-19T07:31:43.4085000Z ==============================================================================
2021-12-19T07:31:43.4124320Z ##[error]A supported task execution handler was not found. The task does not carry an implementation that is compatible with your current operating system 'Windows'. Contact the task author for more details.
2021-12-19T07:31:43.4153704Z ##[section]Finishing: Trigger a new build of Update servers

Our version:
Microsoft Visual Studio Team Foundation Server
Version 16.131.28226.3

Please take a look at this.

**Comment by DavidLeibEricom** [comment] 2021-12-20 09:58
I am also having the same issue

**Comment by mariusmoessmer** [comment] 2021-12-20 10:55
Same here ;-)

**Comment by huserben** [comment] 2021-12-20 11:09
Hi all

I'm sorry for the inconvenience. Are you using Azure DevOps or Azure DevOps Server? If it's server, what version are you using?

What is the agent version that is running the pipelines for you? Is it possible to update the agents that run the pipelines to the latest version - this might fix the problem.

**Comment by mariusmoessmer** [comment] 2021-12-20 12:26
the problem occurs on an on-premise Microsoft Visual Studio Team Foundation Server Version 15.117.27414.0
Agent version is 2.122.1
The problem is that we cannot quickly update to a newer version...

**Comment by huserben** [comment] 2021-12-20 12:30
Thanks @mariusmoessmer 
So manually updating the agent is not an option for you? I saw there is some how-to in the [docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops&tabs=browser#to-update-self-hosted-agents).

I'm not so familiar anymore with those as I'm using the hosted agents.

If that's the case, is there an option that the package is installed manually? So you remain on the latest version that works? Given that newer version will always break as the node6 execution handler had to be changed for the newer system...

**Comment by kedargmnv** [comment] 2021-12-20 16:47
Even we are having the same issue. Earlier version was 3.2.2 and failing with the same error in v3.3.0(upgrade). How can we downgrade to v3.2.2 where its working for us to continue with our daily builds?

**Comment by kedargmnv** [comment] 2021-12-20 17:09
Even we are having the same issue. Earlier version was 3.2.2 and failing with the same error in v3.3.0(upgrade). How can we downgrade to v3.2.2 where its working for us to continue with our daily builds?

**Comment by BreakingTheBug** [comment] 2021-12-20 17:17
Even we are having the same issue. Earlier version was 3.2.2 and failing with the same error in v3.3.0(upgrade). How can we downgrade to v3.2.2 where its working for us to continue with our daily builds?

**Comment by huserben** [comment] 2021-12-20 17:25
@kedargmnv @BreakingTheBug I understand the frustration and I'm working on a new version of the package that lets you chose the task versions.

That said, posting the same question every 15 minutes is not helping to speed up the process ;-)

**Comment by huserben** [comment] 2021-12-20 18:09
So I'm uploading a new version, now there are two major versions of each task available:
- TriggerBuild in version 3 and 4
- Wait and Cancel Build in version 2 and 3

The older version is the task with the soon to be deprecated node6 execution handler. As it seems this is still needed for some Azure DevOps Sever versions and/or outdated pipeline agents.
The specific task versions that should fix that problem are for you are:
- TriggerBuild in version 3.3.1
- WaitForBuild in version 2.2.1
- CancelBuild in version 2.2.1


The new versions will be using the node10 execution handler and it's advised to upgrade, as other agents (like Azure Hosted Agents) will drop support for the older version end of March 2022.

The "older" tasks won't receive any updates anymore in future, so for potential fixes/new features you would need to update to the newest version.

If you install the latest version of the extension, you will be able to chose the major version, either via yaml:
```
- task: TriggerBuild@4
- task: TriggerBuild@3
```

or via the UI if the classic editor is used:
![image](https://user-images.githubusercontent.com/5486874/146812125-c4a791eb-56be-4296-8bb1-26aff950360d.png)

@BreakingTheBug @xpleonix  @mariusmoessmer  @kedargmnv @DavidLeibEricom @Maxim-Krivobokov can you let me know as soon as possible whether this solves your problems?

**Comment by DougDz** [comment] 2021-12-20 18:20
We are experiencing this same issue and are on TFS 2017 locally.  Not in cloud.  Im struggling to figure out how to install the extension and how our existing one broke over the weekend for our scheduled builds.  Our pipelines are all local also.  Once we can get the new one in place will let you know.

**Comment by kedargmnv** [comment] 2021-12-20 19:03
@huserben Thank you! Build is in progress now.

**Comment by DougDz** [comment] 2021-12-20 20:22
This resolved it for us.  Thanks

**Comment by huserben** [comment] 2021-12-21 14:23
Looks like the problem is solved then - I'll close this issue then.

Just one more time, please be aware that the "old" tasks will not receive any update in future, so as soon as you would update your infrastructure and you would be able to move to the latest major version of the tasks, I would advise you to do so to keep getting updates.

**Closed by huserben** 2021-12-21 14:23 UTC
